# Generated by Django 6.0.8 on 2026-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_speakerprofile_job_title_speakerprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_abstention',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='admission_validity_mode',
            field=models.CharField(blank=True, choices=[('inherit', 'Same as product'), ('', 'No check-in time restriction'), ('fixed', 'Fixed start and end'), ('subevent', 'Valid during assigned event date'), ('event', 'Valid during entire event')], default='inherit', help_text='Use "Same as product" to inherit the product mode and overlay only the variation fields you set. Choose "No check-in time restriction" to explicitly clear a product-level restriction for this variation.', max_length=20, verbose_name='Admission validity mode'),
        ),
    ]
