# Generated by Django 6.0.8 on 2026-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_privacy_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_abstention',
            field=models.BooleanField(default=False),
        ),
    ]
