# Generated by Django 6.0.8 on 2026-10-05 13:52

import django.core.validators
import eventyay.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_voucher_all_addons_bundles_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_abstention',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(db_index=True, help_text='Should be short, only contain lowercase letters, numbers, dots, and dashes, and must be unique among your events. We recommend some kind of abbreviation or a date with less than 10 characters that can be easily remembered, but you can also choose to use a random value. This will be used in URLs, order codes, invoice numbers, and bank transfer references.', max_length=50, validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?\\Z'), eventyay.base.validators.EventSlugBanlistValidator()], verbose_name='Short form'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='slug',
            field=models.CharField(db_index=True, help_text='Should be short, only contain lowercase letters, numbers, dots, and dashes. Every slug can only be used once. This is being used in URLs to refer to your organizer accounts and your events.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?\\Z'), eventyay.base.validators.OrganizerSlugBanlistValidator()], verbose_name='Short form'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='admission_validity_mode',
            field=models.CharField(blank=True, choices=[('inherit', 'Same as product'), ('', 'No check-in time restriction'), ('fixed', 'Fixed start and end'), ('subevent', 'Valid during assigned event date'), ('event', 'Valid during entire event')], default='inherit', help_text='Use "Same as product" to inherit the product mode and overlay only the variation fields you set. Choose "No check-in time restriction" to explicitly clear a product-level restriction for this variation.', max_length=20, verbose_name='Admission validity mode'),
        ),
        migrations.AlterField(
            model_name='track',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([0-9A-Fa-f]{3}){1,2}$')], verbose_name='Color'),
        ),
    ]
